INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (1, 'Northwest', 'United States', 'North America');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (2, 'Northeast', 'United States', 'North America');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (3, 'Central', 'United States', 'North America');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (4, 'Southwest', 'United States', 'North America');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (5, 'Southeast', 'United States', 'North America');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (6, 'Canada', 'Canada', 'North America');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (7, 'France', 'France', 'Europe');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (8, 'Germany', 'Germany', 'Europe');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (9, 'Australia', 'Australia', 'Pacific');
INSERT INTO adventureworks.adventureworks_territories (SalesTerritoryKey, Region, Country, Continent) VALUES (10, 'United Kingdom', 'United Kingdom', 'Europe');
